<a href="https://colab.research.google.com/github/Fotrichis/LinearAlgebra_2ndSem/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra
## Laboratory 6 : Matrix Operations

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.Description

In [ ]:
A = np.array([
    [1, 2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [2, 3, 5, 7],
    [5, 2, 1, 2],
    [3, 1, 2, 1]
])
B.shape

(3, 4)

In [ ]:
np.transpose(B).shape

(4, 3)

In [ ]:
B.T.shape

(4, 3)

Own Matrix Transposition

In [ ]:
A = np.array([
    [5,3,6],
    [1,0,3],
    [1,6,1],
    [2,1,3],
])
A.shape

(4, 3)

In [ ]:
np.transpose(A).shape

(3, 4)

In [ ]:
AT = A.T
AT

array([[5, 1, 1, 2],
       [3, 0, 6, 1],
       [6, 3, 1, 3]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1, 2, 3],
    [0, 1, 2],
    [1, 3, 2]
])
Y = np.array([
    [3, 2, 1],
    [2, 1, 0],
    [2, 3, 1]
])

In [ ]:
np.dot(X,Y)

array([[13, 13,  4],
       [ 6,  7,  2],
       [13, 11,  3]])

In [ ]:
X.dot(Y)

array([[13, 13,  4],
       [ 6,  7,  2],
       [13, 11,  3]])

In [ ]:
X @ Y

array([[13, 13,  4],
       [ 6,  7,  2],
       [13, 11,  3]])

In [ ]:
np.matmul(X,Y)

array([[13, 13,  4],
       [ 6,  7,  2],
       [13, 11,  3]])

In [ ]:
A = np.array([
    [2,1,3],
    [1,1,1],
    [2,3,3]
])
B = np.array([
    [3,3,1],
    [1,1,1],
    [2,1,4]
])

In [ ]:
A @ B

array([[13, 10, 15],
       [ 6,  5,  6],
       [15, 12, 17]])

In [ ]:
A.dot(B)

array([[13, 10, 15],
       [ 6,  5,  6],
       [15, 12, 17]])

In [ ]:
np.matmul(A,B)

array([[13, 10, 15],
       [ 6,  5,  6],
       [15, 12, 17]])

In [ ]:
np.dot(A,B)

array([[13, 10, 15],
       [ 6,  5,  6],
       [15, 12, 17]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

## Rule 1: The inner dimensions of the two matrices in question must be the same.

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$E = \begin{bmatrix}1&2&3\\3&3&1\\2&1&3\end{bmatrix}, F = \begin{bmatrix}1&3&1\\2&1&1\\1&1&2\\2&2&1\end{bmatrix}, G = \begin{bmatrix}2&2&3\\1&2&2\\2&1&3\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
E = np.array([
    [1, 2, 3],
    [3, 3, 1],
    [2, 1, 3]
])
F = np.array([
    [1, 3, 1],
    [2, 1, 1],
    [1, 1, 2],
    [2, 2, 1]
])
G = np.array([
    [2, 2, 3],
    [1, 2, 2],
    [2, 1, 3]  
])
print(E.shape)
print(F.shape)
print(G.shape)

(3, 3)
(4, 3)
(3, 3)


In [ ]:
E @ G

array([[10,  9, 16],
       [11, 13, 18],
       [11,  9, 17]])

In [ ]:
F @ G

array([[ 7,  9, 12],
       [ 7,  7, 11],
       [ 7,  6, 11],
       [ 8,  9, 13]])

In [ ]:
E @ F.T

array([[10,  7,  9,  9],
       [13, 10,  8, 13],
       [ 8,  8,  9,  9]])

In [ ]:
H = np.array([
    [1,2,3,4]
])
I = np.array([
    [1,3,4,1]
])
print (H.shape)
print (I.shape)

(1, 4)
(1, 4)


In [ ]:
I.T @ H

array([[ 1,  2,  3,  4],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 1,  2,  3,  4]])

In [ ]:
H @ I.T

array([[23]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,0]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $C$ is denoted as $det(C)$ or $|C|$. So let's say $C$ is represented as:
$$C = \begin{bmatrix}c_{(0,0)}&c_{(0,1)}\\c_{(1,0)}&c_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|C| = c_{(0,0)}*c_{(1,1)} - c_{(1,0)}*c_{(0,1)}$$
So if we have $A$ as:
$$C = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |C| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
C = np.array([
    [1,2],
    [1,3]
])
np.linalg.det(C)

1.0

In [ ]:
D = np.array([
    [1,3,3],
    [2,1,3],
    [2,2,1]
])
np.linalg.det(D)

13.0

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [1,7],
    [-3,5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
  [6, 9, 0],
  [4, 2, -1],
  [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

$A \cdot B \neq B \cdot A$

$$A = \begin{bmatrix}1&2&3&4\\3&3&1&2\\2&1&3&1\\ 1&2&3&5 \\ 1&3&4&2\end{bmatrix}  B = \begin{bmatrix}1&3&1&2&6\\2&1&1&3&4\\1&1&2&3&4\\ 3&5&3&7&2 \end{bmatrix}$$

In [ ]:
A = np.array([
    [1,2,3,4],
    [3,3,1,2],
    [2,1,3,1],
    [1,2,3,5],
    [1,3,4,2]
])

y = len(A)
print("Number of rows in Matrix A : ", y)

B = np.array([
    [1,3,1,2,6],
    [2,1,1,3,4],
    [1,1,2,3,4],
    [3,5,3,7,2]
])

z = len(B[0])
print("Number of columns in Matrix B: ", z)

if y == z:
  print ('A·B :')
  print(A@B)
else:
  print("Not Viable for Operation")

Number of rows in Matrix A :  5
Number of columns in Matrix B:  5
A·B :
[[20 28 21 45 34]
 [16 23 14 32 38]
 [10 15 12 23 30]
 [23 33 24 52 36]
 [17 20 18 37 38]]


In [ ]:
print ('B·A :')
B @ A

B·A :


array([[20, 34, 39, 33],
       [14, 26, 35, 34],
       [15, 25, 35, 31],
       [33, 44, 52, 64]])

In [ ]:
np.array_equal(A @ B,B @ A)

False

$A \cdot (B \cdot C) = (A \cdot B) \cdot C$

$$A = \begin{bmatrix}11&9&5&13\\7&7&5&4\\10&8&6&11\\ 14&2&20&5 \end{bmatrix}  B = \begin{bmatrix}1&4&11&2&8\\21&2&7&6&13\\8&1&5&10&4\\ 14&5&3&7&2 \end{bmatrix} C= \begin{bmatrix}16&3&2&8\\3&9&5&13\\2&8&10&4\\ 12&5&4&6\\6&2&6&7\end{bmatrix}$$


In this case, $A$ has a shape of $(4,4)$, $B$ has a shape of $(4,5)$ and $C$ has a shape of $(5,4)$. In the left side of equation, it is advisable to multiply the $B$ and $C$ first before proceeding to $A$. While on the right side of equation, $A$ and $B$ are the first to be multiplied before proceeding to $C$.

In [ ]:
A = np.array([
    [11,9,5,13],
    [7,7,5,4],
    [10,8,6,11],
    [14,2,20,5]
])

B = np.array([
    [1,4,11,2,8],
    [21,2,7,6,13],
    [8,1,5,10,4],
    [14,5,3,7,2]
])

C = np.array([
    [16,3,2,8],
    [3,9,5,13],
    [2,8,10,4],
    [12,5,4,6],
    [6,2,6,7]
])

In [ ]:
print ('A·(B·C) :')
A @ (B@C)

A·(B·C) :


array([[11754,  6025,  6358,  9143],
       [ 7185,  3677,  4051,  5552],
       [10729,  5510,  5835,  8317],
       [10125,  5898,  6395,  8031]])

In [ ]:
print ('(A·B)·C :')
(A@B) @ C

(A·B)·C :


array([[11754,  6025,  6358,  9143],
       [ 7185,  3677,  4051,  5552],
       [10729,  5510,  5835,  8317],
       [10125,  5898,  6395,  8031]])

In [ ]:
np.array_equal(A @ (B@C),(A@B) @ C)

True

$A\cdot(B+C) = A\cdot B + A\cdot C$

$$A = \begin{bmatrix}10&2&8&9&3\\3&4&16&2&21\\7&11&4&13&4\\ 10&2&4&9&1\end{bmatrix}  B = \begin{bmatrix}1&7&21&2&6\\20&1&9&3&5\\11&1&12&3&7\\ 3&15&9&7&8 \\ 14&1&2&3&3\end{bmatrix} \\C= \begin{bmatrix}9&13&2&8&5\\3&2&15&3&21\\20&2&2&14&4\\ 11&5&4&6&13 \\ 9&2&7&14&6\end{bmatrix}$$

In this given, $A$ has a shape of $(4,5)$, $B$ has a shape of $(5,5)$ and $C$ has a shape of $(5,5)$. In the left side of equation, the $B$ and $C$ are added first since they have a same shape, before multiplying to $A$. While on the right side of equation, $A$ is multiplied by both $B$ and $C$, then add.

In [ ]:
A = np.array([
    [10,2,8,9,3],
    [3,4,16,2,21],
    [7,11,4,13,4],
    [10,2,4,9,1]
])

B = np.array([
    [1,7,21,2,6],
    [20,1,9,3,5],
    [11,1,12,3,7],
    [3,15,9,7,8],
    [14,1,2,3,3]
])

C = np.array([
    [9,13,2,8,5],
    [3,2,15,3,21],
    [20,2,2,14,4],
    [11,5,4,6,13],
    [9,2,7,14,6]
])

In [ ]:
print ('A·(B+C) :')
A @ (B+C)

A·(B+C) :


array([[ 589,  419,  534,  416,  466],
       [1129,  223,  604,  709,  544],
       [ 721,  457,  686,  441,  716],
       [ 419,  401,  460,  314,  404]])

In [ ]:
print ('(A·B)+(A·C) :')
(A@B) + (A@C)

(A·B)+(A·C) :


array([[ 589,  419,  534,  416,  466],
       [1129,  223,  604,  709,  544],
       [ 721,  457,  686,  441,  716],
       [ 419,  401,  460,  314,  404]])

In [ ]:
np.array_equal(A @ (B+C),(A@B) + (A@C))

True

$(B+C)\cdot A = B\cdot A + C\cdot A$

$$A = \begin{bmatrix}9&21&3&1&3&9\\13&2&8&2&16&2\\8&10&2&12&1&7\\ 8&12&8&4&7&5\\ 10&8&1&11&4&7 \end{bmatrix}  B = \begin{bmatrix}11&7&18&2&6&3\\21&2&9&4&5&3\\14&2&10&2&7&10\\ 4&13&8&4&8&13 \\ 10&4&8&4&13&7\\ 1&9&9&4&11&9\end{bmatrix} \\C= \begin{bmatrix}11&3&12&9&4&7\\5&12&10&4&8&7\\18&2&9&10&7&9\\ 10&5&7&9&10&1 \\ 10&4&8&11&3&7\\1&4&18&4&9&10\end{bmatrix}$$

For the 4th property, $A$ has a shape of $(5,6)$, $B$ has a shape of $(6,6)$ and $C$ has a shape of $(6,6)$. Same concept from the previous given is implimented.

In [ ]:
A = np.array([
    [9,21,3,1,3,9],
    [13,2,8,2,16,2],
    [8,10,2,12,1,7],
    [8,12,8,4,7,5],
    [10,8,1,11,4,7]
])

B = np.array([
    [11,7,18,2,6,3],
    [21,2,9,4,5,3],
    [14,2,10,2,7,10],
    [10,4,8,4,13,7],
    [1,9,9,4,11,9]
])

C = np.array([
    [11,3,12,9,4,7],
    [5,12,10,4,8,7],
    [18,2,9,10,7,9],
    [10,5,7,9,10,1],
    [10,4,8,11,3,7],
    [1,4,18,4,9,10]
])

In [ ]:
print ('(B+C)·A :')
(B+C) @ A

(B+C)·A :


array([[ 65,  94, 104, 113,  74,  64],
       [ 53,  68,  86,  96,  69,  50],
       [ 59,  81,  95, 109,  66,  54],
       [106, 126, 132, 178, 103,  70],
       [ 88, 108, 121, 166,  95,  64],
       [ 73, 104, 127, 135,  97,  78]])

In [ ]:
print ('B·A + C·A')
B @ A + C @ A

B·A + C·A


array([[ 65,  94, 104, 113,  74,  64],
       [ 53,  68,  86,  96,  69,  50],
       [ 59,  81,  95, 109,  66,  54],
       [106, 126, 132, 178, 103,  70],
       [ 88, 108, 121, 166,  95,  64],
       [ 73, 104, 127, 135,  97,  78]])

In [ ]:
np.array_equal((B+C) @ A, B @ A + C @ A)

True

$A\cdot I = A$

$$A = \begin{bmatrix}10&8&7&20&1\\4&9&11&7&10\\11&5&8&12&9\\ 8&20&3&4&1 \end{bmatrix}  I = \begin{bmatrix}1&0&0&0&0\\0&1&0&0&0\\0&0&1&0&0\\ 0&0&0&1&0\\ 0&0&0&0&1 \end{bmatrix} $$

The 5th property includes a multiplication of an identity matrix, $A$ has a shape of $(4,5)$ and the identity matrix has a shape of $(5,5$).

In [ ]:
A = np.array([
    [10,8,7,20,1],
    [4,9,11,7,10],
    [11,5,8,12,9],
    [8,20,3,4,1]
])

I = np.array([
    [1,0,0,0,0],
    [0,1,0,0,0],
    [0,0,1,0,0],
    [0,0,0,1,0],
    [0,0,0,0,1]
])

identity = np.identity(I.shape[0])
if((identity == I).all()):
    print('A @ I')
    print(A @ I)
else:
    print('Result will not be equal to the values of the Multiplicand')

A @ I
[[10  8  7 20  1]
 [ 4  9 11  7 10]
 [11  5  8 12  9]
 [ 8 20  3  4  1]]


In [ ]:
np.array_equal(A,A @ I)

True

$A\cdot \emptyset = \emptyset$ 

$$A = \begin{bmatrix}9&8&15&3\\10&6&2&8\\1&9&9&13\\ 6&8&11&4 \end{bmatrix}  \emptyset = \begin{bmatrix}11&2&8&7&9\\20&1&3&6&6\\9&11&4&8&4\\ 3&5&13&7&8 \end{bmatrix} $$

For the last multiplication property, $A$ has a shape of $(4,4)$ and a matrix whose not a zero matrix has a shape of $(4,5)$.

In [ ]:
A = np.array([
    [9,8,15,3],
    [10,6,2,8],
    [1,9,9,13],
    [6,8,11,4]
])

Ø = np.array([
    [11,2,8,7,9],
    [20,1,3,6,6],
    [9,11,4,8,4],
    [3,5,13,7,8]
])

zero = np.zeros(Ø.shape[1])
if((zero == Ø).all()):
    print('Result will become a Zero Matrix')
else:
    print('A · Ø')
    print(A @ Ø)

A · Ø
[[403 206 195 252 213]
 [272  88 210 178 198]
 [311 175 240 224 203]
 [337 161 168 206 178]]


In [ ]:
prod = np.array([
    [403,206,195,252,213],
    [272,88,210,178,198],
    [311,175,240,224,203],
    [337,161,168,206,175]
])


is_all_zero = np.all((prod == 0))
if is_all_zero:
  print('Property denied')
else:
  print('Property accepted')

Property accepted
